name: CI - BPCalculator

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner
        shell: pwsh

      - name: SonarCloud - Begin analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: pwsh
        run: |
          dotnet-sonarscanner begin `
            /k:"kajalDevopsEngineer_CSDCA1_Repo" `
            /o:"kajaldevopsengineer" `
            /d:sonar.login="$env:SONAR_TOKEN" `
            /d:sonar.cs.vscoveragexml.reportsPaths="**/coverage.cobertura.xml"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution (with code analysis)
        run: dotnet build --configuration Debug --no-restore

      - name: Run unit + BDD tests with coverage
        run: dotnet test --collect:"XPlat Code Coverage" --no-build

      - name: SonarCloud - End analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: pwsh
        run: dotnet-sonarscanner end /d:sonar.login="$env:SONAR_TOKEN"


      - name: Check code formatting
        run: dotnet format --verify-no-changes

      - name: Check for vulnerable NuGet packages
        run: dotnet list package --vulnerable || exit 0

      - name: Snyk - Scan for vulnerabilities
        uses: snyk/actions/dotnet@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=medium

