name: CI - BPCalculator

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner
        shell: pwsh

      - name: SonarCloud - Begin analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: pwsh
        run: |
          dotnet-sonarscanner begin `
            /k:"kajalDevopsEngineer_CSDCA1_Repo" `
            /o:"kajaldevopsengineer" `
            /d:sonar.login="$env:SONAR_TOKEN" `
            /d:sonar.cs.vscoveragexml.reportsPaths="**/coverage.cobertura.xml" `
            /d:sonar.exclusions="e2e-tests/**,perf-tests/**" `
            /d:sonar.coverage.exclusions="e2e-tests/**,perf-tests/**"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution (with code analysis)
        run: dotnet build --configuration Debug --no-restore

      - name: Run unit + BDD tests with coverage
        run: dotnet test --collect:"XPlat Code Coverage" --no-build

      - name: SonarCloud - End analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: pwsh
        run: dotnet-sonarscanner end /d:sonar.login="$env:SONAR_TOKEN"

      - name: Check code formatting
        run: dotnet format --verify-no-changes

      - name: Check for vulnerable NuGet packages
        run: dotnet list package --vulnerable || exit 0

      - name: Snyk - Scan for vulnerabilities
        uses: snyk/actions/dotnet@v1
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=medium

  deploy-qa:
    needs: build-test
    runs-on: windows-latest
    environment: qa

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Publish app
        run: dotnet publish BPCalculator/BPCalculator.csproj -c Release -o ./publish

      - name: Deploy to Azure Web App (QA)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bpcalc-qa'   # your QA app name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_QA }}
          package: ./publish
  
  zap-scan:
    needs: deploy-qa
    runs-on: ubuntu-latest
    environment: qa

    steps:
      - name: OWASP ZAP Baseline Scan against QA
        uses: zaproxy/action-baseline@v0.13.0
        continue-on-error: true          
        with:
          target: 'https://bpcalc-qa-g8gyh3h7aedcbkem.uksouth-01.azurewebsites.net/'
          allow_issue_writing: false      
          cmd_options: '-a'               
          artifact_name: ''               
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  perf-tests:
    needs: zap-scan
    runs-on: ubuntu-latest   # k6 action uses Linux runners
    environment: qa

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run k6 load test against QA
        uses: grafana/k6-action@v0.3.1
        with:
          filename: perf-tests/bp-load-test.js
        env:
          BASE_URL: https://bpcalc-qa-g8gyh3h7aedcbkem.uksouth-01.azurewebsites.net/

  e2e-tests:
    needs: perf-tests
    runs-on: windows-latest
    environment: qa

    defaults:
      run:
        working-directory: e2e-tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
        # if you didn't commit package-lock.json yet, use:
        # run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests against QA
        env:
          BASE_URL: https://bpcalc-qa-g8gyh3h7aedcbkem.uksouth-01.azurewebsites.net/
        run: npx playwright test --reporter=line

  deploy-prod:
    needs: e2e-tests        # only run after QA deploy succeeds (later we can also add tests here)
    runs-on: windows-latest
    environment:
      name: production
      url: https://bpcalc-prod-gyd2fzcma3g4fygr.uksouth-01.azurewebsites.net/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Publish app
        run: dotnet publish BPCalculator/BPCalculator.csproj -c Release -o ./publish

      - name: Deploy to Azure Web App (Prod)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bpcalc-prod'   # EXACT name of your Prod app in Azure
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PROD }}
          package: ./publish
